APPROX_BDAYS_PER_MONTH = 21
APPROX_BDAYS_PER_YEAR = 252

APPROX_5MIN_PER_DAY = 78

MONTHS_PER_YEAR = 12
WEEKS_PER_YEAR = 52
QTRS_PER_YEAR = 4

DAILY = 'daily'
WEEKLY = 'weekly'
MONTHLY = 'monthly'
QUARTERLY = 'quarterly'
YEARLY = 'yearly'
FIVE_MIN = '5min'

ANNUALIZATION_FACTORS = {
    DAILY: APPROX_BDAYS_PER_YEAR,
    WEEKLY: WEEKS_PER_YEAR,
    MONTHLY: MONTHS_PER_YEAR,
    QUARTERLY: QTRS_PER_YEAR,
    YEARLY: 1,
    FIVE_MIN: APPROX_5MIN_PER_DAY * APPROX_BDAYS_PER_YEAR
}
